### PR TITLE
remove magic numbers, clean-up formatting.

### PR DESCRIPTION
**Pull request by benpeloquin7**
@TomHardwicke removed magic numbers, cleaned up code / markdown a bit. I think it should be good to go.

### CODE REVIEW

**Comment by TomHardwicke** [comment]
Hi Ben - looks good. I think the only thing missing is reproCheck()s for the descriptive statistics. In this case its a figure so you'll need to do eyeball checks and enter 'figure' for the obtained value. This is all so we have the correct denominator for errors vs values checked at the end of the project.

**Comment by benpeloquin7** [comment]
@TomHardwicke I think the descriptive statistics were just prelim exploration by the pilot authors. (None of those values are mentioned in our `Target outcomes` chunk.) I'm happy to add the `reproChecks()` for them, but it seems like it detracts from the focus on the core analysis? Maybe worth removing those (and anything that doesn't have a `reproCheck` more generally)?

**Comment by TomHardwicke** [comment]
Figure 1 is in the target outcomes though - if a figure or table is mentioned in the target outcomes then we include that

**Comment by benpeloquin7** [comment]
got it!

**Pull request merged**
